import {
  parseScenarioDefinition,
  type DifficultyProfile,
  type ScenarioDefinition,
} from "@/modules/scenario/domain/scenario-definition";

const standardDifficultyProfiles: DifficultyProfile[] = [
  {
    level: 1,
    displayName: "練習",
    hiddenFactRatio: 0.1,
    ambiguityLevel: 1,
    pressureLevel: 0,
    contradictionCount: 0,
    unexpectedQuestionCount: 0,
    responseWaitToleranceSeconds: 45,
    conversationTimeLimitMinutes: 7,
    prohibitedBehaviors: [],
  },
  {
    level: 2,
    displayName: "初級",
    hiddenFactRatio: 0.25,
    ambiguityLevel: 2,
    pressureLevel: 0,
    contradictionCount: 0,
    unexpectedQuestionCount: 1,
    responseWaitToleranceSeconds: 35,
    conversationTimeLimitMinutes: 7,
    prohibitedBehaviors: [],
  },
  {
    level: 3,
    displayName: "標準",
    hiddenFactRatio: 0.45,
    ambiguityLevel: 3,
    pressureLevel: 1,
    contradictionCount: 1,
    unexpectedQuestionCount: 2,
    responseWaitToleranceSeconds: 28,
    conversationTimeLimitMinutes: 7,
    prohibitedBehaviors: [],
  },
  {
    level: 4,
    displayName: "難しい",
    hiddenFactRatio: 0.6,
    ambiguityLevel: 4,
    pressureLevel: 2,
    contradictionCount: 2,
    unexpectedQuestionCount: 3,
    responseWaitToleranceSeconds: 22,
    conversationTimeLimitMinutes: 10,
    prohibitedBehaviors: [],
  },
  {
    level: 5,
    displayName: "実戦",
    hiddenFactRatio: 0.75,
    ambiguityLevel: 5,
    pressureLevel: 3,
    contradictionCount: 3,
    unexpectedQuestionCount: 4,
    responseWaitToleranceSeconds: 18,
    conversationTimeLimitMinutes: 10,
    prohibitedBehaviors: [],
  },
];

const defaultClientTypes = [
  {
    id: "cooperative-client",
    displayName: "協力的な顧客",
    description: "質問に落ち着いて回答し、練習しやすい顧客。",
    cooperationLevel: 5,
    itKnowledgeLevel: 2,
  },
  {
    id: "low-it-knowledge-client",
    displayName: "IT知識が少ない顧客",
    description: "専門用語に弱く、業務の言葉で説明する必要がある顧客。",
    cooperationLevel: 4,
    itKnowledgeLevel: 1,
  },
  {
    id: "deadline-focused-client",
    displayName: "納期重視の顧客",
    description: "納期への関心が強く、影響や代替案を求める顧客。",
    cooperationLevel: 3,
    itKnowledgeLevel: 2,
  },
];

export const technicalMvpScenarioFixtures: ScenarioDefinition[] = [
  parseScenarioDefinition({
    id: "initial-requirements-interview",
    version: 1,
    status: "enabled",
    displayName: "初回要件ヒアリング",
    shortDescription: "初回相談で目的、現行業務、利用者、納期などを確認する。",
    clientTypes: defaultClientTypes,
    facts: [
      {
        id: "current-excel-workflow",
        label: "現行Excel管理",
        content: "現在はExcelで利用者情報と対応履歴を管理している。",
        disclosureRule: "initial",
        importance: "critical",
        expectedQuestionCategories: ["current-workflow"],
      },
      {
        id: "personal-information",
        label: "個人情報",
        content: "氏名、住所、支援記録などの個人情報を扱う。",
        disclosureRule: "direct-question",
        importance: "critical",
        expectedQuestionCategories: ["security", "data-handling"],
      },
      {
        id: "role-based-permissions",
        label: "権限差",
        content: "管理者と一般職員で閲覧・編集できる範囲が異なる。",
        disclosureRule: "deep-question",
        importance: "critical",
        expectedQuestionCategories: ["permission"],
      },
      {
        id: "mobile-usage",
        label: "スマートフォン利用",
        content: "外出先からスマートフォンで記録を確認したい。",
        disclosureRule: "direct-question",
        importance: "normal",
        expectedQuestionCategories: ["usage-environment"],
      },
    ],
    difficultyProfiles: standardDifficultyProfiles,
    scenes: [
      {
        id: "welfare-office-first-call",
        version: 1,
        displayName: "福祉事業所の初回相談",
        description: "小規模な福祉事業所が業務管理システム化を相談する場面。",
        practiceGoals: ["目的確認", "現行業務確認", "重要要件の確認"],
        openingMessage: "Excel管理をシステム化したいのですが、何から相談すればよいでしょうか。",
        requiredFactIds: ["current-excel-workflow", "personal-information", "mobile-usage"],
        criticalFactIds: ["current-excel-workflow", "personal-information", "role-based-permissions"],
        allowedDifficultyLevels: [1, 2, 3, 4, 5],
        allowedClientTypeIds: ["cooperative-client", "low-it-knowledge-client"],
      },
    ],
    evaluationRubric: {
      requiredFactIds: ["current-excel-workflow", "personal-information", "mobile-usage"],
      criticalFactIds: ["current-excel-workflow", "personal-information", "role-based-permissions"],
      successConditionIds: ["confirm-purpose", "identify-critical-facts", "agree-next-action"],
      focusSkillIds: ["ask-questions", "summarize-client-needs", "confirm-agreement"],
    },
  }),
  parseScenarioDefinition({
    id: "scope-change-additional-request",
    version: 1,
    status: "enabled",
    displayName: "仕様変更・追加要望",
    shortDescription: "契約範囲外の追加要望に即答せず、影響確認と回答期限を伝える。",
    clientTypes: defaultClientTypes,
    facts: [
      {
        id: "requested-export-feature",
        label: "追加CSV出力",
        content: "契約範囲外のCSV出力機能を追加したい。",
        disclosureRule: "initial",
        importance: "critical",
        expectedQuestionCategories: ["requested-change"],
      },
      {
        id: "fixed-release-date",
        label: "固定リリース日",
        content: "顧客側の告知済み日程があり、リリース日を変えたくない。",
        disclosureRule: "direct-question",
        importance: "critical",
        expectedQuestionCategories: ["schedule"],
      },
      {
        id: "budget-not-approved",
        label: "追加予算未承認",
        content: "追加費用の社内承認はまだ取れていない。",
        disclosureRule: "deep-question",
        importance: "critical",
        expectedQuestionCategories: ["budget"],
      },
    ],
    difficultyProfiles: standardDifficultyProfiles,
    scenes: [
      {
        id: "csv-export-added-late",
        version: 1,
        displayName: "開発後半のCSV出力追加",
        description: "開発後半で、契約外の機能を納期据え置きで追加したいと言われる場面。",
        practiceGoals: ["即答しない", "影響範囲確認", "回答期限を決める"],
        openingMessage: "このCSV出力くらいなら、今回の範囲で追加できますよね。",
        requiredFactIds: ["requested-export-feature", "fixed-release-date", "budget-not-approved"],
        criticalFactIds: ["requested-export-feature", "fixed-release-date", "budget-not-approved"],
        allowedDifficultyLevels: [1, 2, 3, 4, 5],
        allowedClientTypeIds: ["cooperative-client", "deadline-focused-client"],
      },
    ],
    evaluationRubric: {
      requiredFactIds: ["requested-export-feature", "fixed-release-date", "budget-not-approved"],
      criticalFactIds: ["requested-export-feature", "fixed-release-date", "budget-not-approved"],
      successConditionIds: ["avoid-immediate-promise", "explain-impact-check", "set-response-date"],
      focusSkillIds: ["do-not-answer-immediately", "explain-additional-cost", "set-next-action"],
    },
  }),
  parseScenarioDefinition({
    id: "schedule-delay-explanation",
    version: 1,
    status: "enabled",
    displayName: "納期遅延の説明",
    shortDescription: "遅延を結論から伝え、影響範囲、対応策、新しい期限を説明する。",
    clientTypes: defaultClientTypes,
    facts: [
      {
        id: "delayed-feature",
        label: "遅延対象機能",
        content: "権限管理機能の実装が予定より遅れている。",
        disclosureRule: "initial",
        importance: "critical",
        expectedQuestionCategories: ["delay-target"],
      },
      {
        id: "cause-technical-risk",
        label: "技術的原因",
        content: "既存データの権限ルールに例外が多く、確認が必要になった。",
        disclosureRule: "direct-question",
        importance: "critical",
        expectedQuestionCategories: ["cause"],
      },
      {
        id: "new-deadline",
        label: "新期限",
        content: "追加確認を含め、3営業日の延長が必要。",
        disclosureRule: "deep-question",
        importance: "critical",
        expectedQuestionCategories: ["new-schedule"],
      },
    ],
    difficultyProfiles: standardDifficultyProfiles,
    scenes: [
      {
        id: "permission-feature-delay",
        version: 1,
        displayName: "権限管理機能の遅延報告",
        description: "予定していた権限管理機能が期日までに完了しないことを伝える場面。",
        practiceGoals: ["結論から報告", "原因と対応策の分離", "新期限提示"],
        openingMessage: "本日の進捗報告ですが、予定通り完了していますか。",
        requiredFactIds: ["delayed-feature", "cause-technical-risk", "new-deadline"],
        criticalFactIds: ["delayed-feature", "cause-technical-risk", "new-deadline"],
        allowedDifficultyLevels: [1, 2, 3, 4, 5],
        allowedClientTypeIds: ["cooperative-client", "deadline-focused-client"],
      },
    ],
    evaluationRubric: {
      requiredFactIds: ["delayed-feature", "cause-technical-risk", "new-deadline"],
      criticalFactIds: ["delayed-feature", "cause-technical-risk", "new-deadline"],
      successConditionIds: ["state-delay-first", "separate-cause-action", "offer-new-deadline"],
      focusSkillIds: ["speak-conclusion-first", "apologize-with-action", "confirm-client-concern"],
    },
  }),
  parseScenarioDefinition({
    id: "disabled-demo-scenario",
    version: 1,
    status: "disabled",
    displayName: "Disabled Fixture Scenario",
    shortDescription: "通常選択には表示しない検証用シナリオ。",
    clientTypes: [defaultClientTypes[0]],
    facts: [
      {
        id: "disabled-fact",
        label: "無効fixture",
        content: "表示されないことを確認するための情報。",
        disclosureRule: "initial",
        importance: "normal",
        expectedQuestionCategories: ["disabled"],
      },
    ],
    difficultyProfiles: standardDifficultyProfiles,
    scenes: [
      {
        id: "disabled-scene",
        version: 1,
        displayName: "無効場面",
        description: "通常選択には表示しない場面。",
        practiceGoals: ["表示されないこと"],
        openingMessage: "これは表示されません。",
        requiredFactIds: ["disabled-fact"],
        criticalFactIds: [],
        allowedDifficultyLevels: [1],
        allowedClientTypeIds: ["cooperative-client"],
      },
    ],
    evaluationRubric: {
      requiredFactIds: ["disabled-fact"],
      criticalFactIds: [],
      successConditionIds: ["disabled-success"],
      focusSkillIds: ["disabled-focus"],
    },
  }),
];

